site_name: Praktis dbt
site_url: https://praktisdbt.rendybjunior.com/
site_author: Rendy B. Junior
site_description: "Panduan pemrosesan data dengan dbt beserta praktik nyata dan tips _best practices_."

# Theme settings
theme:
  name: material  # Uses the Material for MkDocs theme
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.path
    - navigation.footer
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extra settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rendybjunior
    - icon: material/heart
      link: https://github.com/sponsors/rendybjunior
      name: Sponsor Me
  #generator: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/sponsor-button.js
  
# Extensions
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - literate-nav  # Allows using folder-based navigation

# Deploy settings
repo_url: https://github.com/rendybjunior/praktisdbt
edit_uri: edit/main/docs/
