site_name: Praktis dbt
site_url: https://praktisdbt.rendybjunior.com/
site_author: Rendy B. Junior
site_description: "Panduan pemrosesan data dengan dbt beserta praktik nyata dan tips _best practices_."

nav:
  - Praktik dbt: index.md
  - Analyses: analyses.md
  - Chapter 1: chapter-1/
  - Cheatsheet: cheatsheet.md

# Theme settings
theme:
  name: material  # Uses the Material for MkDocs theme
  language: id
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book
    favicon: fontawesome/solid/book
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extra settings
extra:
  analytics:
    provider: google
    property: G-EF4W9T5CB1
    feedback:
      title: Apakah halaman ini mudah dipahami?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Mudah
          data: 1
          note: >-
            Terima kasih!
        - icon: material/emoticon-sad-outline
          name: Sulit dipahami
          data: 0
          note: >- 
            Beritahu kami apa kesulitannya <a href="https://forms.gle/8eGzuLeVdNHJPCwZ7" target="_blank" rel="noopener">di sini</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rendybjunior
    - icon: material/heart
      link: https://github.com/sponsors/rendybjunior
      name: Sponsor Me
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/InsinyurData
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rendybjunior/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/rendybjunior
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/rendybjunior/
  #generator: false
copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.id">Lisensi CC BY-SA 4.0</a> | Praktis dbt | rendybjunior
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/sponsor-button.js
  
# Extensions
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

  # Python Markdown Extensions
  #- pymdownx.arithmatex:
  #    generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.caption #https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/caption/
  #/// caption
  #Fruit Count
  #///
  - pymdownx.caret # superscript H^2^0
  - pymdownx.details # ??? note, ??? note+, !!! info inline, !!! info inline end
  - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#using-emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      line_spans: __span
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite # `#!python print('hello')` # https://pygments.org/docs/lexers/
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.keys
  - pymdownx.mark # highlighting using ==mark me== 
  - pymdownx.smartsymbols # https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # subscript CH~3~CH~2~OH
  # strike ~~Delete me~~
  - pymdownx.critic
  # Addition {++ ++}
  # Deletion {-- --}
  # Substitution {~~ ~> ~~}
  # Comment {>> <<}
  # Highlight {== ==}{>> <<}

# Plugins
plugins:
  - git-authors
  - git-revision-date-localized
  - search
  #- search.suggest # experimental
  #- search.highlight # experimental
  - literate-nav  # Allows using folder-based navigation
  - meta # for adding comments to all pages
  - offline
  - social
  - tags
  - glightbox

# Deploy settings
repo_url: https://github.com/rendybjunior/praktisdbt
edit_uri: edit/main/docs/
